; Copyright (c) 2026. All Rights Reserved.
[CoreRedirects]
+PropertyRedirects=(OldName="/Script/DIVERuntime.DIVEInspectableComponent.BuiltInBindings",NewName="/Script/DIVERuntime.DIVEInspectableComponent.Bindings")
+PropertyRedirects=(OldName="/Script/DIVERuntime.DIVEInspectableComponent.BuiltInSections",NewName="/Script/DIVERuntime.DIVEInspectableComponent.Sections")
+PropertyRedirects=(OldName="/Script/DIVERuntime.DIVEInspectableComponent.InlineBindings",NewName="/Script/DIVERuntime.DIVEInspectableComponent.Bindings")
+PropertyRedirects=(OldName="/Script/DIVERuntime.DIVEInspectableComponent.InlineSections",NewName="/Script/DIVERuntime.DIVEInspectableComponent.Sections")
+PropertyRedirects=(OldName="/Script/DIVERuntime.DIVEInspectableComponent.InlineBindings_DEPRECATED",NewName="/Script/DIVERuntime.DIVEInspectableComponent.Bindings")
+PropertyRedirects=(OldName="/Script/DIVERuntime.DIVEInspectableComponent.InlineSections_DEPRECATED",NewName="/Script/DIVERuntime.DIVEInspectableComponent.Sections")
